from elasticsearch import Elasticsearch, helpers

def uploadCsvToCloud():
  # Password for the 'elastic' user generated by Elasticsearch
  ELASTIC_PASSWORD = "1yBJdH5uZavduf6SP8frkfS0"
  # Found in the 'Manage Deployment' page
  CLOUD_ID = "univ_pjt_1t:YXAtbm9ydGhlYXN0LTIuYXdzLmVsYXN0aWMtY2xvdWQuY29tOjQ0MyRhOTE4ZjMyZGM5YzA0NWU5OTg1ZDJlNmNlNzIwOTg4YSRjMzRkYmI0ODA4ZjU0N2E1ODg0MzdlOTUxZjhkN2FiNg=="
  # Create the client instance
  client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
  )


  idx_name = "programmers"

  with open('data.ndjson', 'rt', encoding='UTF-8-sig') as f:
    helpers.bulk(client, f.readlines(), index=idx_name)  # , document = mapping)#,pipeline=pipeline_name)

#uploadCsvToCloud()

