name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and export
      uses: docker/build-push-action@v4
      with:
        #context: .
        tags: myimage:latest
        outputs: type=docker,dest=myimage.tar

    - name: Print working directory
      run: pwd
    - name: List files
      run: ls -al

    - name: Upload AWS s3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_EC2_METADATA_DISABLED: true
      run:
        aws s3 cp --recursive --region ap-northeast-2 dist s3://001-docker-images



#    - name: Push build to S3
#      uses: sai-sharan/aws-s3-sync-action@master
#      with:
#        access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        region: 'ap-northeast-2'
#        source: 'myimage.tar'
#        destination_bucket: ${{ secrets.AWS_BUCKET_NAME }}
#        #destination_prefix: ${{ secrets.DESTINATION_PREFIX }}
#        #exclude: '.git/*'
#        #delete: true
#        #quiet: false


#    - name: Deploying application to Amazon S3
#      uses: dvelasquez/deploy-s3-action@main
#      with:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_DEFAULT_REGION: ap-northeast-2
#          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
#          BUCKET_PATH: "" # Or to upload a pull_request: "/pr/${{github.event.number}}"
#          DIST_LOCATION_CODE: /tmp/myimage.tar

#
#    - name: zip main.py in src/ to current workspace dir
#      run: |
#        CURRENT_DIR=$(pwd)
#        mkdir artifact
#        cd ./aws-wordpress/3-app-configuration/lambda-jumpbox-uptime/src/
#        zip "${CURRENT_DIR}/artifact/lambda-jumpbox-uptime.zip" main.py
#    - name: Custom docker container action to push object to S3
#      uses: ./.github/actions/push-object-to-s3
#      with:
#        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
#        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
#        aws_region: ap-northeast-2
#        aws_s3_bucket_name: 001-docker-images
#        source_file: ./artifact/lambda-jumpbox-uptime.zip
#        destination_path: /
#        destination_file_name: lambda-jumpbox-uptime.zip


#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v1
#
#
#    - name: Build and push
#      #id: docker_build
#      run: docker build . --file Dockerfile --tag crawling:0.1
#
#    - name: Upload AWS s3
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        AWS_EC2_METADATA_DISABLED: true
#      run:
#        aws s3 cp --recursive --region ap-northeast-2 dist s3://001-docker-images